### PR TITLE
correct method naming

### PR DESCRIPTION
**Pull request by ollym**
@HoneyryderChuck can you review/approve? It'll hopefully remove this from our logs...

image

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
Totally forgot about updating this adapter, thx for the nudge @ollym . LGTM 👍

**Comment by janko** [comment]
@HoneyryderChuck Looks like a [missing local variable](https://github.com/janko/down/actions/runs/5013261791/jobs/9023914132?pr=85) in the HTTPX native resolver.

**Comment by janko** [comment]
It's not a blocker, so I'll go ahead and merge this. Thanks for the patch @ollym 🤘🏻

**Comment by HoneyryderChuck** [comment]
Thx, [tracking](https://gitlab.com/os85/httpx/-/issues/235)

**Pull request merged**
